### ISSUE TITLE
Image Error

### ISSUE THREAD

**Issue by trivender** [tpartner/LimeSurvey-Image-Interest-Points-5x#1]

**Comment by tpartner** [comment]
Can you see the _interestPoints.css_ and _interestPoints.css_ files loaded in the page source?

Did you install directly from the git download or did you extract and compress (zip) the **Interest-Points** folder and install that as indicated in the readme?

The file structure should look like this.

![capture-2](https://github.com/tpartner/LimeSurvey-Image-Interest-Points-5x-6x/assets/1437729/40aa7db6-6a73-47f9-bd84-2c3b4970c364)

**Comment by trivender** [comment]
Yes, I can see the interestPoints.css file loaded in the page source.
Yes, I did the same that you indicated in the yellow highlighted point.

But I am unable to get any solution. Also, I am facing the same issue with the “card sorting” question type.

**Comment by tpartner** [comment]
Unfortunately, I cannot debug your issue. 

It works fine for me in LS version 5.6.51+240116

- https://partnersurveys.com/limesurvey5x/index.php/736236?lang=en&newtest=Y

**Comment by trivender** [comment]
Can you please send me the screen recording of the complete process of this question from beginning to end, like how you make the URL and other important related things? 

It will be helpful for me.

**Comment by tpartner** [comment]
Sorry, I don't have time for that.
